services:
  ai-stremio-search:
    image: ghcr.io/mkcfdc/aisearch:latest
    container_name: ai-stremio-search
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    command: [
      "deno",
      "run",
      "--allow-net",
      "--allow-env",
      "--allow-read",
      "--unstable-cron",
      "main.ts",
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ai-stremio-search:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge
