services:
  ai-stremio-search:
    image: aisearch:latest
    container_name: ai-stremio-search
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    depends_on: 
      - ngrok   
    command: [
      "deno",
      "run",
      "--allow-net",
      "--allow-env",
      "--allow-read",
      "--unstable-cron",
      "main.ts",
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ai-stremio-search:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - secure_net
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    env_file:
      - .env
    command:
      - "http"
      - "http://host.docker.internal:3004"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}
    ports:
      - 4040:4040
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge
