name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      - name: Build Vite React App
        working-directory: ./configure
        run: |
          bun install
          bun run build

      - name: Prepare built assets for deployment
        run: cp -R configure/dist server/configure/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
          DENO_PROJECT_ID: ${{ secrets.DENO_PROJECT_ID }}
        run: |
          deno install -qAf --unstable https://deno.land/x/deploy/deployctl.ts
          deployctl deploy --token $DENO_DEPLOY_TOKEN --project $DENO_PROJECT_ID server/main.ts
